import type { ShareDocument } from '../types.js';
import { escapeHtml } from '../utils/html.js';

export interface WebRenderInput {
  document: ShareDocument;
  fontCss: string;
  siteName?: string;
  canonicalUrl?: string;
}

export function renderDefaultWebPage(input: WebRenderInput): string {
  const title = input.document.meta.title ?? inferTitle(input.document);
  const description = inferDescription(input.document);
  const siteName = input.siteName ?? 'iwannashare';
  const canonical = input.canonicalUrl;

  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="${escapeHtml(siteName)}">
  ${canonical === undefined ? '' : `<link rel="canonical" href="${escapeHtml(canonical)}">`}
  ${canonical === undefined ? '' : `<meta property="og:url" content="${escapeHtml(canonical)}">`}
  <style>${input.fontCss}${baseCss()}</style>
</head>
<body>
  <main class="shell">
    <article class="note">
      <h1>${escapeHtml(title)}</h1>
      <div class="content">
        ${input.document.html}
      </div>
    </article>
    <footer class="page-footer">
      <span>iwannashare by nofrish</span>
      <a href="https://nofrish.me">Back to nofrish.me</a>
    </footer>
  </main>
</body>
</html>`;
}

function inferTitle(document: ShareDocument): string {
  const firstLine = document.plainText.split(/[。！？\n]/)[0]?.trim();
  return firstLine || 'Untitled Share';
}

function inferDescription(document: ShareDocument): string {
  const value = document.plainText.replace(/\s+/g, ' ').trim();
  if (value.length <= 120) {
    return value || 'A public share generated by IWannaShare.';
  }

  return `${value.slice(0, 118)}...`;
}

function baseCss(): string {
  return String.raw`
* { box-sizing: border-box; }
html { color-scheme: light; }
:root {
  --body-bg: #efe9dd;
  --text: #264653;
  --muted: rgba(38, 70, 83, 0.62);
  --strong: #19343f;
  --title: #19343f;
  --heading: #2a9d8f;
  --accent: #2a9d8f;
  --rule: rgba(42, 157, 143, 0.24);
  --note-width: 80vw;
  --note-max-width: 960px;
  --body-font: "LXGW Bright", "Songti SC", "STSong", serif;
  --title-font: "LXGW Bright", "Songti SC", "STSong", serif;
  --heading-font: "LXGW Bright", "Songti SC", "STSong", serif;
  --ui-font: "PingFang SC", "Hiragino Sans GB", sans-serif;
  --mono-font: "SFMono-Regular", Consolas, monospace;
  --title-size: 34px;
  --title-min-size: 25px;
  --title-weight: 520;
  --title-gap: 34px;
  --body-size: 19px;
  --body-min-size: 16px;
  --body-weight: 430;
  --line-height: 1.76;
  --paragraph-gap: 1.05em;
  --radius: 18px;
  --callout-padding: 24px 28px;
  --callout-border: 1px solid rgba(42, 157, 143, 0.26);
  --callout-bg: rgba(42, 157, 143, 0.11);
  --callout-text: #264653;
  --callout-shadow: 0 20px 60px -54px rgba(38, 70, 83, 0.38), 0 0 44px -34px rgba(38, 70, 83, 0.34);
  --code-bg: rgba(42, 157, 143, 0.12);
  --code-text: #264653;
}
body {
  margin: 0;
  color: var(--text);
  background:
    radial-gradient(circle at 85% 4%, rgba(42, 157, 143, 0.1), transparent 32%),
    linear-gradient(180deg, #fbf7ee 0%, var(--body-bg) 100%);
  font-family: var(--body-font);
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
}
a {
  color: inherit;
  text-decoration-thickness: 0.08em;
  text-underline-offset: 0.18em;
}
.shell {
  width: min(100%, 1240px);
  margin: 0 auto;
  padding: clamp(24px, 4vw, 58px);
}
.note {
  width: min(var(--note-width), var(--note-max-width));
  margin: 0 auto;
}
h1 {
  margin: 0 0 var(--title-gap);
  padding: 18px 0;
  border-top: 6px double var(--accent);
  border-bottom: 6px double var(--accent);
  color: var(--title);
  font-family: var(--title-font);
  font-size: clamp(var(--title-min-size), 5vw, var(--title-size));
  font-weight: var(--title-weight);
  line-height: 1.14;
  letter-spacing: 0;
}
.content {
  color: var(--text);
  font-size: clamp(var(--body-min-size), 2.2vw, var(--body-size));
  font-weight: var(--body-weight);
  line-height: var(--line-height);
}
.content > *:first-child { margin-top: 0; }
.content p {
  margin: 0 0 var(--paragraph-gap);
}
.content strong {
  color: var(--strong);
  font-weight: 780;
}
.content em {
  color: var(--strong);
}
.content h2 {
  margin: clamp(40px, 7vw, 64px) 0 16px;
  color: var(--heading);
  font-family: var(--heading-font);
  font-size: clamp(21px, 3.4vw, 28px);
  font-weight: 760;
  line-height: 1.25;
  letter-spacing: 0;
}
.content h3 {
  margin: clamp(30px, 6vw, 48px) 0 13px;
  color: var(--strong);
  font-family: var(--heading-font);
  font-size: clamp(19px, 3vw, 24px);
  font-weight: 720;
  line-height: 1.3;
  letter-spacing: 0;
}
.content ul,
.content ol {
  margin: 0 0 var(--paragraph-gap);
  padding-left: 1.35em;
}
.content li {
  margin: 0.28em 0;
  padding-left: 0.15em;
}
.content blockquote,
.content .callout {
  margin: clamp(24px, 6vw, 40px) 0;
  padding: var(--callout-padding);
  border: var(--callout-border);
  border-radius: var(--radius);
  background: var(--callout-bg);
  box-shadow: var(--callout-shadow);
}
.content blockquote p,
.content .callout p {
  margin: 0 0 0.75em;
  color: var(--callout-text);
}
.content blockquote p:last-child,
.content .callout p:last-child {
  margin-bottom: 0;
}
.content .callout-note {
  background: rgba(244, 162, 97, 0.13);
  border-color: rgba(244, 162, 97, 0.28);
}
.content .callout-warning {
  background: rgba(231, 111, 81, 0.13);
  border-color: rgba(231, 111, 81, 0.28);
}
.content code {
  padding: 0.1em 0.28em;
  border-radius: 6px;
  background: var(--code-bg);
  color: var(--code-text);
  font-family: var(--mono-font);
  font-size: 0.88em;
}
.content pre {
  margin: 28px 0;
  padding: 20px 22px;
  overflow-x: auto;
  border: 1px solid var(--rule);
  border-radius: 12px;
  background: rgba(42, 157, 143, 0.08);
}
.content pre code {
  padding: 0;
  background: transparent;
  font-size: 0.92em;
  line-height: 1.65;
}
.content table {
  display: block;
  width: 100%;
  margin: clamp(28px, 7vw, 42px) 0;
  overflow-x: auto;
  border-collapse: collapse;
  font-family: var(--ui-font);
  font-size: clamp(13px, 1.8vw, 15px);
  line-height: 1.55;
}
.content th,
.content td {
  min-width: 120px;
  padding: 12px 14px;
  border-bottom: 1px solid var(--rule);
  text-align: left;
  vertical-align: top;
}
.content th {
  color: var(--strong);
  font-weight: 760;
}
.page-footer {
  width: min(var(--note-width), var(--note-max-width));
  margin: clamp(50px, 10vw, 90px) auto 0;
  padding-top: 22px;
  border-top: 1px solid var(--rule);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  color: var(--muted);
  font-family: var(--ui-font);
  font-size: 14px;
}
@media (max-width: 760px) {
  :root {
    --note-width: 100%;
    --title-size: 32px;
    --body-size: 18px;
  }
  .shell {
    padding: 20px 18px 34px;
  }
  .page-footer {
    align-items: flex-start;
    flex-direction: column;
  }
}
`;
}
